package terminal

import (
	"encoding/json"
	"net/http"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"

	"github.com/creack/pty"
	"golang.org/x/net/websocket"

	"ppt/server-panel/services"
)

type wsMessage struct {
	Type string `json:"type"`
	Cols uint16 `json:"cols"`
	Rows uint16 `json:"rows"`
	Data string `json:"data"`
}

func Handler(sessions *services.SessionService) http.Handler {
	return websocket.Handler(func(ws *websocket.Conn) {
		req := ws.Request()
		cookie, err := req.Cookie(services.SessionCookieName)
		if err != nil {
			_ = ws.Close()
			return
		}

		session, exists := sessions.Get(cookie.Value)
		if !exists || session.Mode != "root" {
			_ = ws.Close()
			return
		}

		targetUsername := req.URL.Query().Get("user")
		var cmd *exec.Cmd
		if targetUsername != "" {
			target, err := user.Lookup(targetUsername)
			if err != nil || target.Username != targetUsername {
				_ = ws.Close()
				return
			}
			cmd = exec.Command("su", "-", targetUsername)
		} else {
			shell := "/bin/bash"
			if _, err := os.Stat(shell); os.IsNotExist(err) {
				shell = "/bin/sh"
			}
			// Panel-scoped prompt: bash reads OUR rc file, which sources the user's
			// own ~/.bashrc first and only then adds the timestamp. SSH and Instance
			// Connect sessions are untouched, and a customised prompt elsewhere can't
			// be clobbered by us. Falls back to a plain shell if the file is missing.
			if rc, err := panelRCFile(); err == nil && shell == "/bin/bash" {
				cmd = exec.Command(shell, "--rcfile", rc)
			} else {
				cmd = exec.Command(shell)
			}
		}
		cmd.Env = append(os.Environ(), "TERM=xterm-256color", "USER="+session.Username)

		ptmx, err := pty.Start(cmd)
		if err != nil {
			_ = ws.Close()
			return
		}
		defer func() {
			_ = ptmx.Close()
			_ = cmd.Process.Kill()
		}()

		// Output loop: PTY -> WS
		go func() {
			buf := make([]byte, 2048)
			for {
				n, err := ptmx.Read(buf)
				if err != nil {
					break
				}
				err = websocket.Message.Send(ws, string(buf[:n]))
				if err != nil {
					break
				}
			}
		}()

		// Input loop: WS -> PTY
		for {
			var msg string
			err := websocket.Message.Receive(ws, &msg)
			if err != nil {
				break
			}

			var wsMsg wsMessage
			if err := json.Unmarshal([]byte(msg), &wsMsg); err == nil {
				switch wsMsg.Type {
				case "input":
					_, _ = ptmx.Write([]byte(wsMsg.Data))
				case "resize":
					_ = pty.Setsize(ptmx, &pty.Winsize{
						Cols: wsMsg.Cols,
						Rows: wsMsg.Rows,
					})
				}
			} else {
				_, _ = ptmx.Write([]byte(msg))
			}
		}
	})
}

// panelRCBody is the rc file bash reads for PANEL terminals only.
//
// It sources the user's own ~/.bashrc first so nothing they configured is lost,
// then adds a timestamp to the prompt. The timestamp sits on the PROMPT rather
// than the typed line deliberately: a prompt is printed when the PREVIOUS command
// finishes, so consecutive prompts bracket how long each command took — which is
// the question worth answering when reading back a long session.
//
// HISTTIMEFORMAT is set alongside it so `history` gains timestamps too, which is
// retroactive and costs nothing.
const panelRCBody = `# Generated by Ppt Server Panel for its web terminal only.
# Your ~/.bashrc is sourced above; SSH sessions do not read this file.
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
PS1='\[\e[90m\]\t\[\e[0m\] '"$PS1"
HISTTIMEFORMAT='%F %T '
`

// panelRCFile writes the panel rc file and returns its path. Rewritten on each
// connection so an edited or deleted file self-heals rather than silently
// serving stale content.
func panelRCFile() (string, error) {
	path := filepath.Join(os.TempDir(), "ppt-panel-bashrc")
	if err := os.WriteFile(path, []byte(panelRCBody), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
